// This file seeds the database with sample matches for testing purposes.
// It includes 10 finished matches with ELO changes and one ongoing match.
// It clears existing matches first, to avoid duplicates on re-seed.
// Then it returns the created matches, so other seed files can reference them.

// The sample data is generated by Claude, but the rest is written by me.

import { Match } from "../../models/Match.js";

export default async function matchSeed(users, categories) {
    await Match.deleteMany({});

    const matches = await Promise.all([
        new Match({
            players: [users[0]._id, users[1]._id],
            gameCategory: categories[0]._id,
            status: "finished",
            startedAt: "2026-03-01T10:00:00.000Z",
            endedAt: "2026-03-01T10:30:00.000Z",
            winner: users[0]._id,
            outcome: "3-1",
            eloChanges: [
                { userId: users[0]._id, delta: 24 },
                { userId: users[1]._id, delta: -24 }
            ]
        }).save(),
        new Match({
            players: [users[2]._id, users[3]._id],
            gameCategory: categories[1]._id,
            status: "finished",
            startedAt: "2026-03-05T14:00:00.000Z",
            endedAt: "2026-03-05T14:45:00.000Z",
            winner: users[3]._id,
            outcome: "3-2",
            eloChanges: [
                { userId: users[2]._id, delta: -18 },
                { userId: users[3]._id, delta: 18 }
            ]
        }).save(),
        new Match({
            players: [users[4]._id, users[5]._id],
            gameCategory: categories[2]._id,
            status: "finished",
            startedAt: "2026-03-10T09:00:00.000Z",
            endedAt: "2026-03-10T09:30:00.000Z",
            winner: users[4]._id,
            outcome: "3-0",
            eloChanges: [
                { userId: users[4]._id, delta: 20 },
                { userId: users[5]._id, delta: -20 }
            ]
        }).save(),
        new Match({
            players: [users[6]._id, users[7]._id],
            gameCategory: categories[3]._id,
            status: "finished",
            startedAt: "2026-03-12T16:00:00.000Z",
            endedAt: "2026-03-12T16:40:00.000Z",
            winner: users[6]._id,
            outcome: "3-2",
            eloChanges: [
                { userId: users[6]._id, delta: 16 },
                { userId: users[7]._id, delta: -16 }
            ]
        }).save(),
        new Match({
            players: [users[8]._id, users[9]._id],
            gameCategory: categories[4]._id,
            status: "finished",
            startedAt: "2026-03-15T11:00:00.000Z",
            endedAt: "2026-03-15T11:35:00.000Z",
            winner: users[9]._id,
            outcome: "3-1",
            eloChanges: [
                { userId: users[8]._id, delta: -22 },
                { userId: users[9]._id, delta: 22 }
            ]
        }).save(),
        new Match({
            players: [users[10]._id, users[11]._id],
            gameCategory: categories[5]._id,
            status: "finished",
            startedAt: "2026-03-18T13:00:00.000Z",
            endedAt: "2026-03-18T13:50:00.000Z",
            winner: users[10]._id,
            outcome: "3-0",
            eloChanges: [
                { userId: users[10]._id, delta: 28 },
                { userId: users[11]._id, delta: -28 }
            ]
        }).save(),
        new Match({
            players: [users[12]._id, users[13]._id],
            gameCategory: categories[6]._id,
            status: "finished",
            startedAt: "2026-03-20T10:00:00.000Z",
            endedAt: "2026-03-20T10:25:00.000Z",
            winner: users[12]._id,
            outcome: "3-1",
            eloChanges: [
                { userId: users[12]._id, delta: 19 },
                { userId: users[13]._id, delta: -19 }
            ]
        }).save(),
        new Match({
            players: [users[14]._id, users[15]._id],
            gameCategory: categories[0]._id,
            status: "finished",
            startedAt: "2026-03-22T15:00:00.000Z",
            endedAt: "2026-03-22T15:40:00.000Z",
            winner: users[14]._id,
            outcome: "3-2",
            eloChanges: [
                { userId: users[14]._id, delta: 21 },
                { userId: users[15]._id, delta: -21 }
            ]
        }).save(),
        new Match({
            players: [users[16]._id, users[17]._id],
            gameCategory: categories[1]._id,
            status: "finished",
            startedAt: "2026-03-25T09:00:00.000Z",
            endedAt: "2026-03-25T09:30:00.000Z",
            winner: users[17]._id,
            outcome: "3-1",
            eloChanges: [
                { userId: users[16]._id, delta: -17 },
                { userId: users[17]._id, delta: 17 }
            ]
        }).save(),
        new Match({
            players: [users[0]._id, users[4]._id],
            gameCategory: categories[2]._id,
            status: "finished",
            startedAt: "2026-03-28T14:00:00.000Z",
            endedAt: "2026-03-28T14:35:00.000Z",
            winner: users[0]._id,
            outcome: "3-0",
            eloChanges: [
                { userId: users[0]._id, delta: 25 },
                { userId: users[4]._id, delta: -25 }
            ]
        }).save(),
        // Ongoing games — currently being played, shown on homepage
        new Match({ players: [users[0]._id, users[1]._id],  gameCategory: categories[0]._id,  status: "ongoing", startedAt: "2026-05-29T10:00:00.000Z" }).save(),
        new Match({ players: [users[2]._id, users[3]._id],  gameCategory: categories[5]._id,  status: "ongoing", startedAt: "2026-05-29T11:00:00.000Z" }).save(),
        new Match({ players: [users[4]._id, users[5]._id],  gameCategory: categories[10]._id, status: "ongoing", startedAt: "2026-05-29T12:00:00.000Z" }).save(),
        new Match({ players: [users[6]._id, users[7]._id],  gameCategory: categories[3]._id,  status: "ongoing", startedAt: "2026-05-29T13:00:00.000Z" }).save(),
        new Match({ players: [users[8]._id, users[9]._id],  gameCategory: categories[8]._id,  status: "ongoing", startedAt: "2026-05-29T14:00:00.000Z" }).save(),
        new Match({ players: [users[10]._id, users[11]._id], gameCategory: categories[2]._id,  status: "ongoing", startedAt: "2026-05-30T08:00:00.000Z" }).save(),
        new Match({ players: [users[12]._id, users[13]._id], gameCategory: categories[7]._id,  status: "ongoing", startedAt: "2026-05-30T09:00:00.000Z" }).save(),
        new Match({ players: [users[14]._id, users[15]._id], gameCategory: categories[11]._id, status: "ongoing", startedAt: "2026-05-30T10:00:00.000Z" }).save(),
        new Match({ players: [users[16]._id, users[17]._id], gameCategory: categories[4]._id,  status: "ongoing", startedAt: "2026-05-30T11:00:00.000Z" }).save(),
        new Match({ players: [users[18]._id, users[19]._id], gameCategory: categories[9]._id,  status: "ongoing", startedAt: "2026-05-30T12:00:00.000Z" }).save(),
        // Waiting games — each user appears in at most one waiting match
        new Match({ players: [users[10]._id], gameCategory: categories[1]._id,  status: "waiting", startedAt: "2026-04-13T08:00:00.000Z" }).save(),
        new Match({ players: [users[11]._id], gameCategory: categories[2]._id,  status: "waiting", startedAt: "2026-04-13T09:00:00.000Z" }).save(),
        new Match({ players: [users[12]._id], gameCategory: categories[4]._id,  status: "waiting", startedAt: "2026-04-13T10:00:00.000Z" }).save(),
        new Match({ players: [users[13]._id], gameCategory: categories[6]._id,  status: "waiting", startedAt: "2026-04-13T11:00:00.000Z" }).save(),
        new Match({ players: [users[14]._id], gameCategory: categories[7]._id,  status: "waiting", startedAt: "2026-04-13T12:00:00.000Z" }).save(),
        new Match({ players: [users[15]._id], gameCategory: categories[9]._id,  status: "waiting", startedAt: "2026-04-13T13:00:00.000Z" }).save(),
        new Match({ players: [users[16]._id], gameCategory: categories[11]._id, status: "waiting", startedAt: "2026-04-13T14:00:00.000Z" }).save(),
        new Match({ players: [users[17]._id], gameCategory: categories[12]._id, status: "waiting", startedAt: "2026-04-13T15:00:00.000Z" }).save(),
        new Match({ players: [users[18]._id], gameCategory: categories[13]._id, status: "waiting", startedAt: "2026-04-13T16:00:00.000Z" }).save(),
        new Match({ players: [users[20]._id], gameCategory: categories[1]._id,  status: "waiting", startedAt: "2026-04-15T09:00:00.000Z" }).save(),
        new Match({ players: [users[21]._id], gameCategory: categories[14]._id, status: "waiting", desiredOpponentElo: 1100, startedAt: "2026-04-14T13:00:00.000Z" }).save(),
    ]);

    console.log("Inserted all matches");
    return matches;
}
