// This file seeds the database with sample trophies for testing purposes.
// It clears existing trophies first, to avoid duplicates on re-seed.
// It then returns the created trophies, so tournament.seed.js can reference them.

// The sample data is generated by Claude, but the rest is written by me.

import { Trophy } from "../../models/Trophy.js";

export default async function seedTrophies() {
    await Trophy.deleteMany({});

    // tournamentId is not set here, because it gets updated in tournament.seed.js
    const trophies = await Promise.all([
        new Trophy({ title: "Spring Championship Trophy", image: "spring-trophy.png" }).save(),
        new Trophy({ title: "Summer Slam Trophy", image: "summer-trophy.png" }).save(),
        new Trophy({ title: "Winter Classic Trophy", image: "winter-trophy.png" }).save(),
        new Trophy({ title: "Valentine's Cup", image: "valentines-trophy.png" }).save(),
        new Trophy({ title: "Autumn Open Trophy", image: "autumn-trophy.png" }).save(),
    ]);

    console.log("Inserted all trophies");
    return trophies;
}