// This file seeds the database with all 18 game categories loaded from gamecategories.json.
// It clears existing categories first, to avoid duplicates on re-seed.
// Then it returns the created categories, so other seed files can reference them.

// The sample data in the json file is generated by Claude, but the rest is written by me.

import { GameCategory } from "../../models/GameCategory.js";
import gameCategoryRawData from "./gamecategories.json" with { type: "json"};

export default async function gameCategorySeed(){
    await GameCategory.deleteMany({});

    const gameCategoryDocs = gameCategoryRawData.map(gameCategory => new GameCategory(gameCategory));
    const gameCategories = await Promise.all(gameCategoryDocs.map(gameCategory => gameCategory.save()));
    
    console.log("Inserted all categories")

    return gameCategories
}