// This file seeds the database with sample tournaments for testing purposes.
// It clears existing tournaments first, to avoid duplicates on re-seed.
// After creating the tournaments, it updates the trophies with the real tournament IDs
// since the tournament didn't exist yet when the trophies were created.
// It then returns the created tournaments, so other seed files can reference them.

// The sample data is generated by Claude, but the rest is written by me.

import { Tournament } from "../../models/Tournament.js";
import { Trophy } from "../../models/Trophy.js";

export default async function seedTournaments(users, categories, trophies) {
    await Tournament.deleteMany({});

    const tournaments = await Promise.all([
        new Tournament({
            title: "Spring Championship",
            description: "First tournament of the year",
            date: "2026-04-01T10:00:00.000Z",
            breaks: 10,
            numberOfRounds: 3,
            gameCategory: categories[0]._id,
            participants: [users[0]._id, users[1]._id, users[2]._id, users[3]._id],
            status: "upcoming",
            trophy: trophies[0]._id
        }).save(),
        new Tournament({
            title: "Summer Slam",
            description: "Hot summer tournament",
            date: "2026-06-01T10:00:00.000Z",
            breaks: 15,
            numberOfRounds: 5,
            gameCategory: categories[6]._id,
            participants: [users[4]._id, users[5]._id, users[6]._id, users[7]._id],
            status: "upcoming",
            trophy: trophies[1]._id
        }).save(),
        // DEMO TOURNAMENT — edit this to test 
        // Players: chacha (users[23]) vs asianmaster (users[22])
        //
        // To change when the first round fires, edit the date line:
        //   new Date(Date.now() + 30 * 1000)   → 30 seconds from seed
        //   new Date(Date.now() + 2 * 60 * 1000) → 2 minutes from seed
        //   new Date("2026-06-02T14:00:00")    → specific time
        //
        // To skip the countdown and test ongoing state immediately, change:
        //   status: "upcoming"  → the tournament auto-starts when date arrives
        //   status: "ongoing"   → already started (rounds array will be empty until knockoutRounds runs)
        
        new Tournament({
            title: "Demo Open — Play Now!",
            description: "Open tournament — join and it starts automatically once 2 players are in. The date is set to the past so it fires immediately.",
            date: new Date(Date.now() - 10 * 1000), // ← already in the past so it starts as soon as 2 players join
            breaks: 1,    // ← 1 minute break between rounds (change to 0 for instant next-round)
            numberOfRounds: 2,
            gameCategory: categories[6]._id,
            participants: [], // ← no pre-seeded players, join via the Join button
            status: "upcoming",
            trophy: trophies[2]._id
        }).save()
    ]);

    // update trophies with real tournament IDs
    await Trophy.findByIdAndUpdate(trophies[0]._id, { tournamentId: tournaments[0]._id });
    await Trophy.findByIdAndUpdate(trophies[1]._id, { tournamentId: tournaments[1]._id });
    await Trophy.findByIdAndUpdate(trophies[2]._id, { tournamentId: tournaments[2]._id });
    console.log("Updated trophies with tournament IDs");

    console.log("Inserted all tournaments");
    return tournaments;
}