// This file seeds the database with sample tournaments for testing purposes.
// It clears existing tournaments first, to avoid duplicates on re-seed.
// After creating the tournaments, it updates the trophies with the real tournament IDs
// since the tournament didn't exist yet when the trophies were created.
// It then returns the created tournaments, so other seed files can reference them.

// The sample data is generated by Claude, but the rest is written by me.

import { Tournament } from "../../models/Tournament.js";
import { Trophy } from "../../models/Trophy.js";

export default async function seedTournaments(users, categories, trophies) {
    await Tournament.deleteMany({});

    const tournaments = await Promise.all([
        // Already finished — played in spring, safe to browse without triggering auto-start
        new Tournament({
            title: "Spring Championship",
            description: "First tournament of the year",
            date: "2026-04-01T10:00:00.000Z",
            breaks: 10,
            numberOfRounds: 3,
            gameCategory: categories[0]._id,
            participants: [users[0]._id, users[1]._id, users[2]._id, users[3]._id],
            status: "finished",
            trophy: trophies[0]._id
        }).save(),
        // Upcoming — date is one week from now so it stays upcoming until then
        new Tournament({
            title: "Summer Slam",
            description: "Hot summer tournament",
            date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
            breaks: 15,
            numberOfRounds: 5,
            gameCategory: categories[6]._id,
            participants: [users[4]._id, users[5]._id, users[6]._id, users[7]._id],
            status: "upcoming",
            trophy: trophies[1]._id
        }).save(),
        // Demo tournament: starts 2 minutes after seeding so there is time to join before it auto-starts
        new Tournament({
            title: "Demo Open — Play Now!",
            description: "A live demo tournament you can join and play. It starts automatically 2 minutes after the server seeds the database.",
            date: new Date(Date.now() + 2 * 60 * 1000),
            breaks: 5,
            numberOfRounds: 3,
            gameCategory: categories[6]._id,
            participants: [], // ← no pre-seeded players, join via the Join button
            status: "upcoming",
            trophy: trophies[2]._id
        }).save()
    ]);

    // update trophies with real tournament IDs
    await Trophy.findByIdAndUpdate(trophies[0]._id, { tournamentId: tournaments[0]._id });
    await Trophy.findByIdAndUpdate(trophies[1]._id, { tournamentId: tournaments[1]._id });
    await Trophy.findByIdAndUpdate(trophies[2]._id, { tournamentId: tournaments[2]._id });
    console.log("Updated trophies with tournament IDs");

    console.log("Inserted all tournaments");
    return tournaments;
}