// This file seeds the database with sample tournaments for testing purposes.
// It clears existing tournaments first, to avoid duplicates on re-seed.
// After creating the tournaments, it updates the trophies with the real tournament IDs
// since the tournament didn't exist yet when the trophies were created.
// It then returns the created tournaments, so other seed files can reference them.

// The sample data is generated by Claude, but the rest is written by me.

import { Tournament } from "../../models/Tournament.js";
import { Trophy } from "../../models/Trophy.js";

export default async function seedTournaments(users, categories, trophies) {
    await Tournament.deleteMany({});

    const tournaments = await Promise.all([
        new Tournament({
            title: "Spring Championship",
            description: "First tournament of the year",
            date: "2026-04-01T10:00:00.000Z",
            breaks: 10,
            numberOfRounds: 3,
            gameCategory: categories[0]._id,
            participants: [users[0]._id, users[1]._id, users[2]._id, users[3]._id],
            status: "upcoming",
            trophy: trophies[0]._id
        }).save(),
        new Tournament({
            title: "Summer Slam",
            description: "Hot summer tournament",
            date: "2026-06-01T10:00:00.000Z",
            breaks: 15,
            numberOfRounds: 5,
            gameCategory: categories[6]._id,
            participants: [users[4]._id, users[5]._id, users[6]._id, users[7]._id],
            status: "upcoming",
            trophy: trophies[1]._id
        }).save()
    ]);

    // update trophies with real tournament IDs
    await Trophy.findByIdAndUpdate(trophies[0]._id, { tournamentId: tournaments[0]._id });
    await Trophy.findByIdAndUpdate(trophies[1]._id, { tournamentId: tournaments[1]._id });
    console.log("Updated trophies with tournament IDs");

    console.log("Inserted all tournaments");
    return tournaments;
}