// This file seeds the database with sample comments on matches and tournaments for testing purposes.
// It clears the existing comments first, to avoid duplicates on re-seed.
// The sample data is generated by Claude, but the rest is written by me.

import { Comment } from "../../models/Comment.js";

export default async function seedComments(users, tournaments, matches) {
    await Comment.deleteMany({});

    await Promise.all([
        // Finished games (matches[0-9])
        new Comment({ targetId: matches[0]._id, targetType: "match", comment: "What a great game, well played!", userId: users[0]._id }).save(),
        new Comment({ targetId: matches[0]._id, targetType: "match", comment: "That last roll was unbelievable!", userId: users[1]._id }).save(),
        new Comment({ targetId: matches[0]._id, targetType: "match", comment: "Good game, rematch soon?", userId: users[2]._id }).save(),
        new Comment({ targetId: matches[1]._id, targetType: "match", comment: "That final round was intense!", userId: users[1]._id }).save(),
        new Comment({ targetId: matches[1]._id, targetType: "match", comment: "I didn't see that coming at all.", userId: users[3]._id }).save(),
        new Comment({ targetId: matches[2]._id, targetType: "match", comment: "Classic match, loved watching this one.", userId: users[0]._id }).save(),
        new Comment({ targetId: matches[2]._id, targetType: "match", comment: "The straights rule really changes the strategy.", userId: users[2]._id }).save(),
        new Comment({ targetId: matches[3]._id, targetType: "match", comment: "So close! One die away from winning.", userId: users[4]._id }).save(),
        new Comment({ targetId: matches[3]._id, targetType: "match", comment: "Great pressure under the 3-second timer.", userId: users[1]._id }).save(),
        new Comment({ targetId: matches[4]._id, targetType: "match", comment: "Best of 7 really tests your consistency.", userId: users[3]._id }).save(),
        new Comment({ targetId: matches[5]._id, targetType: "match", comment: "Dominant performance!", userId: users[2]._id }).save(),
        new Comment({ targetId: matches[6]._id, targetType: "match", comment: "Didn't expect that outcome.", userId: users[5]._id }).save(),
        new Comment({ targetId: matches[7]._id, targetType: "match", comment: "What a comeback in the last round!", userId: users[6]._id }).save(),
        new Comment({ targetId: matches[8]._id, targetType: "match", comment: "Tight game all the way through.", userId: users[7]._id }).save(),
        new Comment({ targetId: matches[9]._id, targetType: "match", comment: "3-0 sweep, impressive stuff.", userId: users[4]._id }).save(),

        // Ongoing games (matches[10-15])
        new Comment({ targetId: matches[10]._id, targetType: "match", comment: "This one is heating up!", userId: users[0]._id }).save(),
        new Comment({ targetId: matches[10]._id, targetType: "match", comment: "Anyone else watching this live?", userId: users[2]._id }).save(),
        new Comment({ targetId: matches[11]._id, targetType: "match", comment: "Go dragonslayer!", userId: users[3]._id }).save(),
        new Comment({ targetId: matches[12]._id, targetType: "match", comment: "Exciting match so far.", userId: users[5]._id }).save(),
        new Comment({ targetId: matches[13]._id, targetType: "match", comment: "The 30-second timer makes this so tense.", userId: users[1]._id }).save(),

        // Waiting games (matches[16-17])
        new Comment({ targetId: matches[16]._id, targetType: "match", comment: "Join this one, it's a good variant!", userId: users[0]._id }).save(),
        new Comment({ targetId: matches[17]._id, targetType: "match", comment: "Waiting for a worthy opponent!", userId: users[2]._id }).save(),

        // Tournaments
        new Comment({ targetId: tournaments[0]._id, targetType: "tournament", comment: "Looking forward to this tournament!", userId: users[2]._id }).save(),
        new Comment({ targetId: tournaments[0]._id, targetType: "tournament", comment: "Who's the favourite to win this one?", userId: users[0]._id }).save(),
        new Comment({ targetId: tournaments[0]._id, targetType: "tournament", comment: "My money is on the top seed!", userId: users[4]._id }).save(),
        new Comment({ targetId: tournaments[1]._id, targetType: "tournament", comment: "Good luck everyone!", userId: users[3]._id }).save(),
        new Comment({ targetId: tournaments[1]._id, targetType: "tournament", comment: "Already signed up, can't wait!", userId: users[1]._id }).save(),
    ]);

    console.log("Inserted all comments");
}