// This file seeds the database with sample users loaded from users.json.
// It clears existing users first, to avoid duplicates on re-seed.
// It then returns the created users, so other seed files can reference them.

// The sample data in the json file is generated by Claude, but the rest is written by me.

import { User } from "../../models/User.js";
import usersRawData from "./users.json" with { type: "json"};

export default async function seedUsers() {
    await User.deleteMany({});
    
    const userDocs = usersRawData.map(user => new User(user));
    const users = await Promise.all(userDocs.map(user => user.save()));
    
    console.log("Inserted all users");
    
    return users;
}

